// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rfcomm.protoc
// Protobuf C++ Version: 6.32.0-dev

#include "rfcomm.protoc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace carplay {
namespace bt {

inline constexpr RfcommPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        direction_{static_cast< ::carplay::bt::RfcommTransportDirection >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR RfcommPacket::RfcommPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RfcommPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RfcommPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RfcommPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RfcommPacketDefaultTypeInternal() {}
  union {
    RfcommPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RfcommPacketDefaultTypeInternal _RfcommPacket_default_instance_;
}  // namespace bt
}  // namespace carplay
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_rfcomm_2eprotoc[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rfcomm_2eprotoc = nullptr;
const ::uint32_t
    TableStruct_rfcomm_2eprotoc::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::carplay::bt::RfcommPacket, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::carplay::bt::RfcommPacket, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::carplay::bt::RfcommPacket, _impl_.direction_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::carplay::bt::RfcommPacket)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::carplay::bt::_RfcommPacket_default_instance_._instance,
};
const char descriptor_table_protodef_rfcomm_2eprotoc[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rrfcomm.protoc\022\ncarplay.bt\"X\n\014RfcommPac"
    "ket\022\017\n\007payload\030\001 \001(\014\0227\n\tdirection\030\002 \001(\0162"
    "$.carplay.bt.RfcommTransportDirection*8\n"
    "\030RfcommTransportDirection\022\013\n\007UNKNOWN\020\000\022\006"
    "\n\002IN\020\001\022\007\n\003OUT\020\0022]\n\020CarplayBtService\022I\n\017R"
    "fcommTransport\022\030.carplay.bt.RfcommPacket"
    "\032\030.carplay.bt.RfcommPacket(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_rfcomm_2eprotoc_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rfcomm_2eprotoc = {
    false,
    false,
    278,
    descriptor_table_protodef_rfcomm_2eprotoc,
    "rfcomm.protoc",
    &descriptor_table_rfcomm_2eprotoc_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rfcomm_2eprotoc::offsets,
    file_level_enum_descriptors_rfcomm_2eprotoc,
    file_level_service_descriptors_rfcomm_2eprotoc,
};
namespace carplay {
namespace bt {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RfcommTransportDirection_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rfcomm_2eprotoc);
  return file_level_enum_descriptors_rfcomm_2eprotoc[0];
}
PROTOBUF_CONSTINIT const uint32_t RfcommTransportDirection_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class RfcommPacket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RfcommPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_._has_bits_);
};

RfcommPacket::RfcommPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RfcommPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:carplay.bt.RfcommPacket)
}
PROTOBUF_NDEBUG_INLINE RfcommPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::carplay::bt::RfcommPacket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_) {}

RfcommPacket::RfcommPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RfcommPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RfcommPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RfcommPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.direction_ = from._impl_.direction_;

  // @@protoc_insertion_point(copy_constructor:carplay.bt.RfcommPacket)
}
PROTOBUF_NDEBUG_INLINE RfcommPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_(arena) {}

inline void RfcommPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.direction_ = {};
}
RfcommPacket::~RfcommPacket() {
  // @@protoc_insertion_point(destructor:carplay.bt.RfcommPacket)
  SharedDtor(*this);
}
inline void RfcommPacket::SharedDtor(MessageLite& self) {
  RfcommPacket& this_ = static_cast<RfcommPacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RfcommPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RfcommPacket(arena);
}
constexpr auto RfcommPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RfcommPacket),
                                            alignof(RfcommPacket));
}
constexpr auto RfcommPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RfcommPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RfcommPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RfcommPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RfcommPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RfcommPacket>(), &RfcommPacket::ByteSizeLong,
              &RfcommPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_._cached_size_),
          false,
      },
      &RfcommPacket::kDescriptorMethods,
      &descriptor_table_rfcomm_2eprotoc,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RfcommPacket_class_data_ =
        RfcommPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RfcommPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RfcommPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RfcommPacket_class_data_.tc_table);
  return RfcommPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
RfcommPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RfcommPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::carplay::bt::RfcommPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .carplay.bt.RfcommTransportDirection direction = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RfcommPacket, _impl_.direction_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_.direction_)}},
    // bytes payload = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_.payload_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes payload = 1;
    {PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .carplay.bt.RfcommTransportDirection direction = 2;
    {PROTOBUF_FIELD_OFFSET(RfcommPacket, _impl_.direction_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RfcommPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:carplay.bt.RfcommPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.payload_.ClearNonDefaultToEmpty();
  }
  _impl_.direction_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RfcommPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RfcommPacket& this_ = static_cast<const RfcommPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RfcommPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RfcommPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:carplay.bt.RfcommPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes payload = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_payload().empty()) {
      const ::std::string& _s = this_._internal_payload();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // .carplay.bt.RfcommTransportDirection direction = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_direction() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_direction(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:carplay.bt.RfcommPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RfcommPacket::ByteSizeLong(const MessageLite& base) {
  const RfcommPacket& this_ = static_cast<const RfcommPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RfcommPacket::ByteSizeLong() const {
  const RfcommPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:carplay.bt.RfcommPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // bytes payload = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_payload());
      }
    }
    // .carplay.bt.RfcommTransportDirection direction = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_direction() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_direction());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RfcommPacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RfcommPacket*>(&to_msg);
  auto& from = static_cast<const RfcommPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:carplay.bt.RfcommPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_payload().empty()) {
        _this->_internal_set_payload(from._internal_payload());
      } else {
        if (_this->_impl_.payload_.IsDefault()) {
          _this->_internal_set_payload("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_direction() != 0) {
        _this->_impl_.direction_ = from._impl_.direction_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RfcommPacket::CopyFrom(const RfcommPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:carplay.bt.RfcommPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RfcommPacket::InternalSwap(RfcommPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  swap(_impl_.direction_, other->_impl_.direction_);
}

::google::protobuf::Metadata RfcommPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace bt
}  // namespace carplay
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rfcomm_2eprotoc),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
